spring:
  application:
    name: ${APP_NAME:sample-hex-arch}
  profiles:
    active: local

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000

# configurações do actuator
info:
  app:
    name: sample-hex-arch
    description: Amostra de um simples programa em arquitetura hexagonal
    version: ${project.version}
management:
  endpoints:
    web:
      exposure:
        include: health,info

api:
  adviceslip:
    base-url: https://api.adviceslip.com/advice